apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: topology-example
  janus-idp.io/tekton: topology-example
  backstage.io/kubernetes-id: topology-example
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: topology-example
resources:
  - application-dev.yaml