apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: topology-example
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: topology-example
  name: topology-example
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: topology-example
    weight: 100
  wildcardPolicy: None
